version: 1

formatters:
  basic:
    class: pims.logger.StdoutFormatter
    format: "[%(process)s][%(threadName)s] %(message)s"
  complete:
    class: pims.logger.StdoutFormatter
    format: "[%(asctime)s][%(levelname)s][%(process)s][%(threadName)s] %(message)s"

handlers:
  console:
    class: pims.logger.PimsHandler
    level: INFO
    formatter: basic
    rich_tracebacks: True
    markup: True

loggers:
  pims:
    level: WARNING
  pims.app:
    level: INFO
  pyvips:
    level: ERROR
  uvicorn:
    level: INFO
  uvicorn.access:
    level: CRITICAL
  gunicorn.error:
    propagate: true
  cytomine.client:
    level: INFO

root:
  handlers: [console]
  level: INFO
