ARG  VERSION_NUMBER
FROM cytomine/pims-dependencies:v$VERSION_NUMBER

COPY . /app

WORKDIR /app
RUN pip3 install /app

RUN pip3 install coverage

WORKDIR /app/tests

CMD coverage run --omit=/usr/* -m pytest ; coverage xml ; rm -f app/ci/code-coverage-reports/coverage.xml ; mv /app/tests/coverage.xml /app/ci/code-coverage-reports

